# Generated by Django 6.0 on 2026-01-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoo', '0002_etudiant_sexe_friend_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
