# Generated by Django 6.0 on 2026-01-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoo', '0005_alter_friend_friend_alter_friend_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cursus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
