# Generated by Django 6.0 on 2026-01-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoo', '0006_alter_employe_campus_alter_employe_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
    ]
