# Generated by Django 6.0 on 2026-01-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoo', '0008_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='statut',
            field=models.CharField(blank=True, choices=[('Étudiant', 'Étudiant'), ('Employé', 'Employé')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
